### PR TITLE
Optimise binary size

### PR DESCRIPTION
**Pull request by patrobinson**
We noticed this gem is quite large, 194mb. Part of that is due to the gem duplicating libraries for each version (I'll raise a seperate issue for that). But at 64MB they're not small.

On my M2 mac this change reduced the size by 66%. I gleaned them from https://oknozor.github.io/blog/optimize-rust-binary-size/.
I did try adding `lto = "fat"` but that made the build times very slow.
I tried the other optimisations as well:

Parameters | Size | Build time
----------- | ----- | ---------
original        | 50MB | 1268.79s
opt-level-s | 44M | -
opt-level-z | 26M | 843.22s
opt-level-2 | 49MB | -
opt-level-3 | 50MB | -
opt-level-z-codegen-units-1 | 22MB | 591.98s

### CODE REVIEW

**Comment by catkins** [comment]
>  Part of that is due to the gem duplicating libraries for each version (I'll raise a seperate issue for that).

👏 Even this improvement will be great for our docker image size (and in turn ECS Fargate deploy time).

```
du -h lib/polars/3.*/*
 71M	lib/polars/3.0/polars.bundle
 71M	lib/polars/3.1/polars.bundle
 71M	lib/polars/3.2/polars.bundle
```

**Comment by catkins** [comment]
@ankane, any thoughts on @patrobinson's proposed optimisation here?

**Comment by ankane** [comment]
Hi @patrobinson, thanks for the PR. It'd be great to reduce the size, but changing the opt-level will affect performance, so it's not really possible to do this without understanding the impact.

Also, the gem needs to include a shared library for each minor version of Ruby, as the Ruby ABI isn't stable across minor versions, and Rubygems doesn't have a way to provide different gems for different minor versions.

**Comment by patrobinson** [comment]
@ankane I'm happy to give writing some benchmarks a shot, in a seperate PR, if that will help progress this work? Do you have any thoughts on what would be useful to measure the performance of?

**Comment by ankane** [comment]
Testing a few common methods like `read_csv`, `groupby`, and `join` would be a good start, but in general, I think it probably makes sense to use a similar optimization level as the Python library (which produces a similar size shared library right now).

**Comment by catkins** [comment]
Right, so the default opt-level is `3` for the default `release` profile

https://doc.rust-lang.org/cargo/reference/profiles.html#release

And py-polars is leaving that as default.

https://github.com/pola-rs/polars/blob/81e9be610dd4e650b1499ef5eb34dc6f3b3b1535/py-polars/Cargo.toml#L226-L239

**Comment by catkins** [comment]
https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html I wonder if we'll see any improvements in the next rust version?

**Pull request closed without merging**
